x-custom-metadata:
  version: 1.0.0
  last-updated: 2025-13-11

services:
  alpine:
    image: alpine:latest
    container_name: alpine_test
    command: ["tail", "-f", "/dev/null"]
    networks:
      k8s-dev:
        ipv4_address: 142.18.0.6 

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      k8s-dev:
        ipv4_address: 142.18.0.2  #Docker reserves 1 to gateway
    volumes:
      - ./sonar/conf/sonar.properties:/opt/sonarqube/conf/sonar.properties:ro
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    ports:
      - '9000:9000'   # external port:internal port
      - '8600:8600/tcp'
      - '8600:8600/udp'
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data_dev:/data
    ports:
      - '9001:9000'
      - '9444:9443'
    restart: unless-stopped
    networks:
      k8s-dev:
        ipv4_address: 142.18.0.3

  jenkins:
    image: jenkins/jenkins:2.528.2-lts-jdk21
    container_name: jenkins
    volumes:
      - ./jenkins/conf:/var/jenkins_home
    ports:
      - '8080:8080'
      - '50000:50000'
    restart: on-failure
    networks:
      k8s-dev:
        ipv4_address: 142.18.0.4

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - '1025:1025' #SMTP
      - '8025:8025' #Web UI
    networks:
      k8s-dev:
        ipv4_address: 142.18.0.5

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_temp:
  portainer_data_dev:

networks:
    k8s-dev:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 142.18.0.0/24

